name: Compress images
on:
  push:
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"
jobs:
  compress:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Compress images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
