name: Calibre
# Run this action only when image files are changed and every Saturday.
on:
  pull_request:
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"
  schedule:
    - cron: "* * * * SAT"
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
