name: Clean PNG files
on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.png'
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '14'
      - name: Install optipng
        run: npm install optipng-bin --global
      - name: Clean PNG files
        run: |
          mapfile -t DirtyFiles < <( find $GITHUB_WORKSPACE -type f -and -iname "*.png" )

          for File in "${DirtyFiles[@]}"; do
            optipng "$File" -out "$File" -v -clobber;
          done
      - name: Commit cleaned PNG files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git commit --all --message "Clean PNG files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
