name: Compress WebP files
on:
  push:
    paths:
      - '**.webp'
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install webp
        run: sudo apt-get install webp
      - name: Compress WebP files
        run: |
          mapfile -t UncrompressedFiles < <( find $GITHUB_WORKSPACE -type f -and -iname "*.webp" )

          for File in "${UncrompressedFiles[@]}"; do
            cwebp "$File" -o "$File" -v;
          done
      - name: Commit compressed WebP files
        run: |
          git config --global user.name 'Florin Ungur'
          git config --global user.email 'hello@florinungur.com'
          git commit --all --message "Compress WebP files"
          git push
