name: Generate sitemap.xml
on: workflow_call
jobs:
  # has to be first because of this:
  # https://github.com/florinungur/florinungur.com/actions/runs/5857617165/job/15879856418#step:3:178
  # TODO: set this up locally
  generate-rss:
    uses: ./.github/workflows/generate-rss.yml
  generate-sitemap:
    runs-on: ubuntu-latest
    needs:
      - generate-rss
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1.9.1
        with:
          base-url-path: https://florinungur.com/
          drop-html-extension: true
      - name: Commit sitemap.xml
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git commit --all --message "Generate sitemap.xml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
