name: Minify CSS files
on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.css'
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '14'
      - name: Install cssnano, postcss, and postcss-cli
        run: npm install cssnano postcss postcss-cli --save-dev
      - name: Minify CSS files
        run: npx postcss "css/" --verbose --dir "css/" --use cssnano --no-map
      - name: Commit minified CSS files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git commit --all --message "Minify CSS files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
