name: Minify CSS
on:
  push:
    branches: [ master ]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Globally install cssnano, postcss, and postcss-cli
        run: npm install --global cssnano postcss postcss-cli
      - name: Minify css files
        run: postcss "$GITHUB_WORKSPACE/css/*.css" --dir "$GITHUB_WORKSPACE/css/" --replace --verbose
      - name: Commit minified CSS files
        run: |
          git config --global user.name 'Florin Ungur'
          git config --global user.email 'hello@florinungur.com'
          git commit --all --message "Minify CSS files"
          git push
