name: Minify CSS
on:
  push:
    branches: [ master ]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install cssnano, postcss, and postcss-cli
        run: npm install --save-dev cssnano postcss postcss-cli
      - name: Minify css files
        run: postcss "css/" --verbose --dir "css/"
      - name: Commit minified CSS files
        run: |
          git config --global user.name 'Florin Ungur'
          git config --global user.email 'hello@florinungur.com'
          git commit --all --message "Minify CSS files"
          git push
