name: SVG Optimizer
on:
  push:
    paths:
      - "**.svg"
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Compress SVGs
        uses: ericcornelissen/svgo-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
