name: SVGOptimizer
# Run this action only when SVG files are changed and every Saturday.
on:
  pull_request:
    paths:
      - "**.svg"
  push:
    paths:
      - "**.svg"
  schedule:
    - cron: "* * * * SAT"
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Optimize SVGs
        uses: ericcornelissen/svgo-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
